### ISSUE TITLE
Using React Components as Blaze Templates

### ISSUE THREAD

**Issue by dferber90** [grovelabs/meteor-react#10]
The "official" package `reactjs:react` enables developers to use React components as Blaze templates. I think this feature would be useful for this package, too. That's why I created [dferber:react-create-blaze-template](https://github.com/dferber90/meteor-react-create-blaze-template).

Maybe you could hint to this package in `README.md`? I could also send a PR that simplifies the example using this package. Let me know if this is something you are interested in.

**Comment by lourd** [comment]
Nice! I like keeping those functions separate. Happy to take the pull request adding a referral to your package for the use case

**Comment by dferber90** [comment]
Whoops, missed the notification on this one.
There turned out to be some issues with detecting `componentWillUnmount`. Also MDG is working on official react packages that provide this functionality as well. I will not send a PR as I don't use  _dferber:react-create-blaze-template_ myself anymore. Thanks anyways :+1:
