### ISSUE TITLE
Fine-grained Reactivity

### ISSUE THREAD

**Issue by ccorcos** [grovelabs/meteor-react#4]
Hey, I just thought I'd mention [I've been working with react for a little while](https://github.com/ccorcos/meteor-react-utils) and maybe there are a few features you'd might like to integrate into this package:

One thing this package could benefit from is fine-grained reactive state:

```
getReactiveState: {
  posts: function() {...}
  selected: function() {...}
}
```

**Comment by lourd** [comment]
I don't follow, what do you mean?

**Comment by ccorcos** [comment]
In your example in the README:

```
getReactiveState: function() {
    return {
      friends: Friends.find().fetch(),
      loggedIn: !!Meteor.user()
    }
  },
```

This will run whenever a friend changes or the user logs in/out.

```
getReactiveState: {
      friends: function() { Friends.find().fetch() },
      loggedIn: function() { !!Meteor.user() }
    }
```

This format (like template helpers) allows for fine-grained reactivity.

**Comment by lourd** [comment]
In either situation the [`Tracker.autorun` that's calling `getReactiveState`](https://github.com/grovelabs/meteor-react/blob/master/src/ReactiveMixin.js#L22) will still be re-ran. It's not any more fine-grained to wrap them in functions

**Comment by ccorcos** [comment]
Take the following situation:

```
getReactiveState: {
  posts: function() {return Posts.find().fetch()}
  users: function() {
    users = Meteor.users.find().fetch()
    // do a bunch or work, transforms, whatever...
    return something
  }
}
```

if a post changes, the posts autorun will rerun, but not the users autorun. Thus we have a more efficient implementation.

[What I did is create a separate autorun for each](https://github.com/ccorcos/meteor-react-utils/blob/master/src/utils.coffee#L117), queue up changes in `partialState`, and [call `setState` on `Tracker.afterFlush`](https://github.com/ccorcos/meteor-react-utils/blob/master/src/utils.coffee#L170).

Its just a suggestion. Its up to you whether you like it or not.

**Comment by lourd** [comment]
Ah ok I see, interesting. I wonder what the tradeoff is like having more autoruns vs fetching the reactive state more often. Accumulating partial state and then calling `Tracker.afterFlush` is logically harder to follow, in addition to the state variables being functions that need to be called instead of just data to be used. Maybe it's worth it if the performance gain is significant. My hunch is that state is cheap to fetch but I'd be happy to be proven wrong.

**Comment by ccorcos** [comment]
https://forums.meteor.com/t/react-package-for-meteor/2565
