### ISSUE TITLE
Meteor launch babel error

### ISSUE THREAD

**Issue by madshargreave** [grovelabs/meteor-react#7]
I get the following error message when I run 'meteor'

While loading plugin `compile6to5` from package `grigio:babel`:
   native: Unexpected token /
   at Object.parse (native)
   at Package (packages/compile6to5/plugin/compile-6to5.js:54:1)
   at <runJavaScript-71>:83:4
   at <runJavaScript-71>:90:3

I tried removing the JSX extension from the babel.json file, but this doesnt work. It seems to work if i change the extensions from JSX to JS on seemingly random files

Any ideas?

**Comment by lourd** [comment]
Looks like it's erroring out trying to parse your `babel.json` file. Try a JSON validator, I usually use http://jsonlint.com

**Comment by madshargreave** [comment]
Right, for some reason I had convinced myself that JS comments were allowed in JSON files, thanks for saving my sanity.

**Comment by lourd** [comment]
:+1:  Yeah it's not in the JSON spec but some implementations allow it cause it is definitely useful (like [mup](https://www.npmjs.com/package/mup)).

**Comment by sebastianconcept** [comment]
Thanks for writing about this. Happened to me too.
