### ISSUE TITLE
Updating subscriptions based on changing state

### ISSUE THREAD

**Issue by madshargreave** [grovelabs/meteor-react#9]
Hello

I am trying to implement infinite scrolling on a list of objects, but I am unsure what the best pattern for doing this is.

I have an click event which should increment an `offset` state, which then should be used as a limit when subscribing to a meteor collection.

Currently I have my meteor subscriptions wrapped in the `subscriptions` function, but this only seem to get run when mounting the component, so I'm not sure how to update it.

```
subscriptions: function() {
    console.log('subscribing');

    var user            = Meteor.user();
    var preferences     = !user || user.preferences;
    var activeChannelId = !preferences || preferences.activeChannelId;
    var mine            = true
    var threadLimit     = 20;

    if (this.state) {
      threadLimit = this.state.threadLimit;
    }

    return [
      Meteor.subscribe('commentThreads', activeChannelId, mine, threadLimit),
    ]
  },
```

```
getInitialState: function() {
    return {
      threadLimit: 20
    };
  },
```

Is this the correct approach, or should I perhaps put the subscription inside the `componentDidUpdate`?

**Comment by GageBachik** [comment]
+1 need answer to something similar.
Need to what's being returned in the getReactiveState function for a filter.
ex user picks a new filter. need view to now watch for docs in that filter criteria instead of all docs.

**Comment by lourd** [comment]
Hi @madshargreave, great question. So basically you want to update your subscriptions based on some changing state of the component. This is a great use case, it's been fun to think about.

We need the `subscriptions` method, or more accurately the [`Tracker.autorun` that wraps `subscriptions`](https://github.com/grovelabs/meteor-react/blob/master/src/DDPMixin.js#L37) to run when the state of the component has changed. I see 3 ways to approach implementing this, depending on if you're storing your state with a [Reactive Data Source](http://docs.meteor.com/#/full/reactivity) or on the component's state.

If you use a reactive data source as a parameter to `Meteor.subscribe` within `subscriptions`, then the autorun will automatically track that dependency and re-run appropriately. If you use the component's state, i.e. `this.state` though, then we have to explicitly tell the autorun to re-run.

How do we tell the autorun to re-run? With a `Tracker.Dependency`. If we add a dependency within the Tracker.autorun (`dep = new Tracker.Dependency()`), somewhere we can call `dep.changed()` triggering a re-run.

Now, does the mixin call `dep.changed()` or should the component? Either way, it should probably be called within `componentWillUpdate`. If the mixin does it, it will cast a wide net and call it every time the component updates. If the component does it, you can explicitly check if certain state changed and call it yourself. 

What are the tradeoffs?
- If the mixin calls `dep.changed()` I'm unsure about performance impact of re-running subscriptions every time. 
- Having the component be responsible for calling `dep.changed()` is a little more imperative than I'd like. We should strive to be as declarative as possible.

I'll make some code samples and post them

**Comment by lourd** [comment]
Alright, with the new version you'll want to do

``` js
getInitialState: function() {
  threadLimit: new ReactiveVar(20)
},

subscriptions: function() {
    console.log('subscribing');

    var user            = Meteor.user();
    var preferences     = !user || user.preferences;
    var activeChannelId = !preferences || preferences.activeChannelId;
    var mine            = true;
    var threadLimit     = this.state.threadLimit.get(); // Reactive data source

    return Meteor.subscribe('commentThreads', activeChannelId, mine, threadLimit);
},
```

And then whenever you want to increment the thread limit in a component handler you'll do something like

``` js
handleClick: function() {
  var current = this.state.threadLimit.get();
  this.state.threadLimit.set(current + 10);
}
```

Don't have to worry about tracking state dependencies, that's what Tracker is for! Just use ReactiveVars (or any reactive data source) and it'll re-run on its own.

**Comment by madshargreave** [comment]
Thanks for the detailed reply. I have now updated to the most recent version and made the changes to my code, but for some reason, React does not rerender the component once the initial subscription have been made.

**Comment by lourd** [comment]
You're welcome!

Interesting. Can you post the code?

##

**Comment by madshargreave** [comment]
Nevermind, it was me who was screwing up.

On another note, do you have a suggestion on how best to check if a specific subscription is ready?

I know `this.subsReady()` returns true if all subscriptions within the subscription function are ready, but I need a little more control.

I figured I might set a reactive var inside each `Meteor.subscribe` to flag that it is ready, but maybe you have a preferable approach?

**Comment by lourd** [comment]
I would recommend tracking that within React's state instead of using ReactiveVar. 

``` js
subscriptions: function() {
  var handle1 = Meteor.subscribe('allThings');
  var handle2 = Meteor.subscribe('lotsMoreThings');
//  this.setState({
//    allThingsSub: handle1,
//    lotsMoreThingsSub: handle2
//  });
  // or just pass the boolean
  this.setState({
    thingSubReady: handle1.ready(),
    lotsMoreSubReady: handle2.ready()
  });
  return [handle1, handle2];
}
```
